### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by matteoraggi** [rpellerin/Remote-Control-via-SMS#1]
1 )Is it working with a 64 bit systems?
2) I don't understand this text: "< Android Lollipop 5.0" does it works with android 5.0 and above?

**Comment by rpellerin** [comment]
1. Normally yes.
2. "only < Android Lollipop 5.0" means the feature which allows you to remotely enable 3G or 4G will only work with versions of Android below 5.0; in other words this feature won't work on your phone if you're running Android Lollipop or Marshmallow.
